root: true
env:
  node: true
  es2021: true
  jest/globals: true
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
overrides:
  - files:
      - __tests__/**/*.ts
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
    rules:
      filenames/match-regex: 'off'
rules:
  i18n-text/no-en: 'off'
  no-restricted-syntax:
    - error
    - selector: TSEnumDeclaration
      message: Don't declare enums.
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: ^_
  prettier/prettier: 'off'
  no-mixed-operators: error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-readonly-parameter-types':
    - error
    - ignoreInferredTypes: true
  # See https://zenn.dev/teppeis/articles/2023-04-typescript-5_0-verbatim-module-syntax for enabling reason
  '@typescript-eslint/consistent-type-imports': 'error'
  '@typescript-eslint/no-import-type-side-effects': 'error'
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
