name: 'wait-other-jobs'
description: 'Waits for all or specific other jobs, even if they are defined in other workflows'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
    default: ${{ github.token }}
  own-job-prefix:
    description: 'Typically needed in matrix jobs, will ignore to wait jobs in same workflow which has this prefix'
    required: false
    # Intentionally avoided to set jobId for default
    # default: ${{ github.job }}
  wait-seconds-before-first-polling:
    description: 'Wait this seconds before first polling'
    required: false
    default: '10'
  min-interval-seconds:
    description: 'Wait this interval or the multiplied value (and jitter)'
    required: false
    default: '15'
  early-exit:
    description: 'Stop to rest pollings if faced at least 1 bad condition'
    required: false
    default: 'true'
  retry-method:
    description: 'How to wait for next polling'
    required: false
    default: 'equal_intervals'
  attempt-limits:
    description: 'Stop rest pollings if reached to this limit'
    required: false
    default: '1000' # Enough large
  wait-list:
    description: 'Wait only these jobs'
    required: false
    default: '[]'
  skip-list:
    description: 'Wait except these jobs'
    required: false
    default: '[]'
  skip-same-workflow:
    description: 'Skip jobs defined in the same workflow for example which using this action'
    required: false
    default: 'false'
  dry-run:
    description: 'Avoid http requests for tests'
    required: false
    default: 'false'
outputs:
  dump:
    description: |
      A file path for collected resources which keeps fields than logged.
      This data is only provided for debugging purposes, so the schema is not defined.

runs:
  using: 'node20'
  main: 'dist/index.js'
