name: 'wait-other-jobs'
description: 'Waits for all or specific other jobs, even if they are defined in other workflows'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
    default: '${{ github.token }}'
  github-api-url:
    description: 'Github API URL'
    required: true
    default: '${{ github.api_url }}'
  wait-seconds-before-first-polling: # TODO: Since v4.x, Rename or fallback to `initial-duration` and make it possible to take ISO 8601 duration format. See GH-821
    description: 'Wait this seconds before first polling'
    required: false
    default: '10' # TODO: Since v4.x, Consider setting shorter or 0 because using `equal_intervals` by default. Or respect the `min-interval-seconds` if this value is empty. See GH-596 and GH-994
  min-interval-seconds: # TODO: Since v4.x, Rename or fallback to `least-interval` and make it possible to take ISO 8601 duration format. See GH-821
    description: 'Wait this interval or the multiplied value (and jitter)'
    required: false
    default: '15'
  early-exit:
    description: 'Stop rest pollings if faced at least 1 bad condition'
    required: false
    default: 'true'
  retry-method:
    description: 'How to wait for next polling'
    required: false
    default: 'equal_intervals' # Changed the default from `exponential_backoff` since GH-596(v2)
  attempt-limits:
    description: 'Stop rest pollings if reached to this limit'
    required: false
    default: '1000' # Enough large
  event-list:
    description: |
      - Set a JSON array or special string "all".
      - "all" is the same behavior that worked until v3.
      - Wait only listed events.
      - Empty list is invalid.
      - This value will be inherited in wait and skip lists as a default value.
    required: true
    default: '["${{ github.event_name }}"]'
  wait-list:
    description: 'Wait only these jobs'
    required: false
    default: '[]'
  skip-list:
    description: 'Wait except these jobs'
    required: false
    default: '[]'
  skip-same-workflow:
    description: 'Skip jobs defined in the same workflow which using this action'
    required: false
    default: 'false'
  dry-run:
    description: 'Avoid http requests for tests'
    required: false
    default: 'false'
outputs:
  dump:
    description: |
      A file path for collected resources which keeps fields than logged.
      This data is only provided for debugging purposes, so the schema is not defined.

runs:
  using: 'node20'
  main: 'dist/index.js'
