name: 'wait-other-jobs'
description: 'Waits for all or specific other jobs, even if they are defined in other workflows'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
    default: '${{ github.token }}'
  github-api-url:
    description: 'Github API URL'
    required: true
    default: '${{ github.api_url }}'
  warmup-delay:
    description: |
      Wait this time before first polling.
      To make sure other jobs are running and can be targeted.
      Should be specified with ISO 8601 duration format.
    required: false
    # See GH-596 and GH-994
    # Allow users to use `0`, but avoid `0` as default value:
    #   Pros: Faster execution with `equal_intervals`
    #   Cons: May miss jobs that start after this job begins
    default: 'PT1S'
  minimum-interval:
    description: |
      Wait for this or a longer interval between each poll to reduce GitHub API calls.
      Should be specified with ISO 8601 duration format.
    required: false
    # Allow users to use shorter values, but recommends to set PT4S or greater with considering https://github.com/github/docs/blob/c26f36dbabb133b263c0f979f257b31d6c979341/data/reusables/rest-api/primary-rate-limit-github-token-in-actions.md
    default: 'PT10S'
  early-exit:
    description: 'Stop rest pollings if faced at least 1 bad condition'
    required: false
    default: 'true'
  retry-method:
    description: 'How to wait for next polling'
    required: false
    # Changed the default from `exponential_backoff` since GH-596(v2)
    # Short `warmup-delay` with `exponential_backoff` can result in longer total wait times
    default: 'equal_intervals'
  attempt-limits:
    description: 'Stop rest pollings if reached to this limit'
    required: false
    default: '1000' # Enough large
  event-list:
    description: |
      - Set a JSON array.
      - Wait only listed events.
      - Empty list means "any" events.
      - This value will be ignored in wait and skip lists.
    required: true
    default: '[ "${{ github.event_name }}" ]'
  wait-list:
    description: 'Wait only these jobs'
    required: false
    default: '[]'
  skip-list:
    description: 'Wait except these jobs'
    required: false
    default: '[]'
  skip-same-workflow:
    description: 'Skip jobs defined in the same workflow which using this action'
    required: false
    default: 'false'
  dry-run:
    description: 'Avoid http requests for tests'
    required: false
    default: 'false'
outputs:
  parameters:
    description: |
      Parsed values from `with` and some context.
      This data is only provided for testing, so the schema is not defined.
  dump:
    description: |
      A file path for collected resources which keeps fields than logged.
      This data is only provided for debugging, so the schema is not defined.

runs:
  # Available since https://github.com/actions/runner/releases/tag/v2.327.1
  using: 'node24'
  main: 'dist/index.js'
