name: 'wait-other-jobs'
description: 'Wait finishes for other jobs in GitHub Actions. When they have been finished, this step exit 0 or 1.'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
    default: ${{ github.token }}
  min-interval-seconds:
    description: 'Wait this interval or the multiplied value (and jitter) for next polling'
    required: false
    default: '30'
  early-exit:
    description: 'Stop to rest pollings if faced at least 1 bad condition'
    required: false
    default: 'true'
  retry-method:
    description: 'How to wait for next polling'
    required: false
    default: 'exponential_backoff'
  attempt-limits:
    description: 'Stop rest pollings after this limits even if other jobs are not yet completed'
    required: false
    default: '1000' # Enough large
  dry-run:
    description: 'Avoid http requests for tests'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
