name: 💧
on: [pull_request, push, workflow_dispatch]
permissions:
  contents: read
jobs:
  betterleaks:
    timeout-minutes: 15
    name: betterleaks
    runs-on: ubuntu-slim
    env:
      CLI_VERSION: '1.1.2' # selfup {"extract":"\\d[^']+","replacer":["betterleaks", "version"]}
    steps:
      # betterleaks is a successor of gitleaks.
      # betterleaks is MIT licensed, while gitleaks-action is unfree since v2.
      # Don't refer the unfree code even if used in personal repositories.
      # However I also don't use nixpkgs version here. The Nix footprint is much annoy for this purpose.
      # So simply uses the pre-built CLI here.
      - name: Download
        working-directory: ${{ runner.temp }}
        env:
          GH_TOKEN: ${{ github.token }}
        # Prefer the gh command over curl to avoid hitting GitHub's API rate limit
        run: |
          gh release download 'v${{ env.CLI_VERSION }}' --skip-existing --repo betterleaks/betterleaks --pattern '*_linux_x64.*' --pattern 'checksums.txt'
          sha256sum --check --ignore-missing checksums.txt
      - name: Install
        working-directory: ${{ runner.temp }}
        run: |
          tar zxvf 'betterleaks_${{ env.CLI_VERSION }}_linux_x64.tar.gz'
          mkdir --parents /home/runner/.betterleaks/bin
          mv betterleaks /home/runner/.betterleaks/bin
          echo '/home/runner/.betterleaks/bin' >> $GITHUB_PATH
      - name: Make sure installed betterleaks version
        run: 'betterleaks version'
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0 # Getting all refs for git mode
          persist-credentials: false
      - name: Run
        # For CI use in public repositories, ensuring full-redact does not ensure to avoid actual problems, should not forget it :)
        run: |
          betterleaks git . --redact=100
