name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.editorconfig'
      - '**.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.editorconfig'
      - '**.md'
      - '.vscode/**'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: read
  actions: read

jobs:
  all:
    timeout-minutes: 15
    runs-on: ubuntu-26.04
    steps:
      - name: Generate token
        id: generate-token
        if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.APP_ID }} # TODO: Switch to client-id
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.generate-token.outputs.token || github.token }}
          persist-credentials: true
      - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
      - name: Install direnv
        run: |
          url="$(nix eval --raw --impure --expr '(builtins.fromJSON (builtins.readFile ./flake.lock)).nodes.nixpkgs.locked.url')"
          nix profile add "${url}#direnv"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      # See https://github.com/actions/setup-node/blob/802632921f8532d2409ae6eac3313b6f81f11122/src/cache-utils.ts#L30-L38
      - name: Get pnpm store path
        id: get-pnpm-path
        run: |
          echo "pnpm-store-path=$(nix develop --command pnpm store path --silent)" | tee -a "$GITHUB_OUTPUT"
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache pnpm store
        with:
          path: |
            ${{ steps.get-pnpm-path.outputs.pnpm-store-path }}
          key: |
            pnpm_store-pnpm_${{ hashFiles('pnpm-lock.*') }}-flake_${{ hashFiles('flake.lock') }}-${{ runner.arch }}-${{ runner.os }}
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache deno modules
        with:
          # Using `deno info --json` prints accurate data. However this is a simple solution in this workflow
          # See https://github.com/actions/cache/blob/1bd1e32a3bdc45362d1e726936510720a7c30a57/examples.md?plain=1#L144-L155
          path: |
            ~/.cache/deno
          key: |
            deno_store-deno_${{ hashFiles('deno.lock') }}-flake_${{ hashFiles('flake.lock') }}-${{ runner.arch }}-${{ runner.os }}
      - name: Setup
        run: |
          deno task setup
      - name: Test, build, lint
        run: |
          deno task all
      - name: Fix and commit if diff exists
        if: steps.generate-token.outputs.token != ''
        shell: bash
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          if ! (git add --intent-to-add . && git diff --exit-code); then
            gh pr checkout ${{ github.event.pull_request.number }}
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Fix lint or build diff"
            git push origin HEAD
            echo "Pushed fixes. Failing this run to wait for the next CI run and prevent premature auto-merge."
            exit 1
          fi
      - name: Make sure there is no diff after build
        if: steps.generate-token.outputs.token == ''
        run: |
          deno task check_no_git_diff
