name: 💂➕
on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  dependency-review:
    timeout-minutes: 15
    runs-on: ubuntu-slim
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          # https://spdx.org/licenses/
          allow-licenses: MIT, BSD-3-Clause, BSD-2-Clause, 0BSD, Unlicense, ISC, Apache-2.0, CC-BY-4.0
          allow-dependencies-licenses: pkg:githubactions/NixOS/nix-installer-action
