name: GH-771 - Targets
on:
  push:
    paths:
      - '**GH-771**'
      - 'action.yml'
      - 'dist/**'
  pull_request:
    paths:
      - '**GH-771**'
      - 'action.yml'
      - 'dist/**'

# Disable all permissions in workflow global as to setup clean room
# However PRs will have read permissions because this project is on a public repository
permissions: {}

jobs:
  echo:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    timeout-minutes: 5
    steps:
      - name: Print note
        run: |
          echo 'Triggered by ${{ github.event_name }} event'
          echo 'See https://github.com/kachick/wait-other-jobs/issues/771 for the detail'
