name: hadolint
on:
  push:
    branches: [main]
    paths:
      - '**Dockerfile'
      - '**.dockerfile'
      - '.github/workflows/hadolint.yml'
  pull_request:
    paths:
      - '**Dockerfile'
      - '**.dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: 'true'
          dockerfile: .devcontainer/Dockerfile
