name: hadolint
on:
  push:
    branches: [main]
    paths:
      - '**Dockerfile'
      - '**.dockerfile'
      - '.github/workflows/hadolint.yml'
  pull_request:
    paths:
      - '**Dockerfile'
      - '**.dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          recursive: 'true'
          dockerfile: .devcontainer/Dockerfile
